spring:
  application:
    name: Employee Management System
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
  jpa: # jpa configuration
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  flyway:
    baseline-on-migrate: true

